[project]
name = "capnp-stub-generator"
version = "2.1.1"
description = "Cap'n Proto stub generator"
readme = "README.md"
requires-python = ">=3.10,<4.0"
license = { file = "LICENSE" }
authors = [
  { "name" = "Adrian Figueroa", "email" = "adrian.figueroa@metirionic.com" },
]
dependencies = ["pycapnp", "ruff", "pytest"]

[project.scripts]
capnp-stub-generator = "capnp_stub_generator.cli:main"

[build-system]
requires = ["poetry-core>=2.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
target-version = "py310"
[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = ["E501"]
